### ISSUE TITLE
Source name could be a hyperlink

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#281]
Some rows in the signature table link to another document, or even a named anchor in another document.

These got converted ok, but the DITA was non-compliant, since the `target` document was missing.

* [x] modify mock data to include URL for source
* [x] modify mock data to include URL and anchor for source
* [x] produce document containing content that gets linked to
* [x] prevent parser from generating URLs for source names
* [ ] when documents are linked, do these checks on document:
    * [ ] it's not the current document
    * [ ] the document hasn't already been converted to DITA 
* [ ] if checks pass, convert target document (waiting for #289)
* [ ] provide link to target document

**TODO: @IanMayo to reproduce this page of reference content.  Also reproduce page of data linked from that reference page data.**

Note: the model for this is class A7, with links to docs of type A8

**Comment by IanMayo** [comment]
Suitable data generated in #286

**Comment by IanMayo** [comment]
This is handled with our new strategy.
